spring:
  datasource:
    url: jdbc:mysql://mysql:3306/bookstore
    username: root
    password: Mouni@29
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

